lucaslorentz/caddy-docker-proxy

README.md
plugin/generator.go
plugin/generator_test.go

Closes https://github.com/lucaslorentz/caddy-docker-proxy/issues/11
Changes:
* Add support for proxying directly to containers, without swarm services
@ibnesayeed Can you please take a look?

Add support for proxying containers

---

plugin/loader.go

Loader was initialized before caddy invokes it, that was causing 2 problems:
- When run unit tests it was connecting to docker and printing to console
- It was always logging first caddyfile content to stdout, not respecting `-log file` caddy argument
@ibnesayeed

Delay loader initialization until caddy calls it

---

.gitignore
plugin/generator.go
plugin/loader.go

This PR changes caddy-docker-proxy to listen to docker events in order to update caddy almost immediately: 100ms delay.

Listen to docker events and allow fallback to other caddy loaders

---

glide.yaml
plugin/generator.go
plugin/generator_test.go

I've been using the tasks dns instead of service VIP and it worked much more stable.
Sometimes I was getting a `no route` error and caddy can't reach the service VIP. I don't know the reason.

Add option to proxy service tasks instead of service VIP

---

build.sh
plugin/generator.go

Fixes https://github.com/lucaslorentz/caddy-docker-proxy/issues/59
@ptman what do you think?
I'm not sure if we should check swarm availability only once and cache it.
Or if we should check it every time, that way if the node is disconnected from swarm we nicely handle that with a comment on Caddyfile instead of errors.

Skip services monitoring when swarm is not available

---

README.md
plugin/generator.go
plugin/generator_test.go

Fixes: https://github.com/lucaslorentz/caddy-docker-proxy/issues/12
It's not possible to retrieve ports from docker service, we need a container instance to know it, and containers might not run on the manager we're running caddy proxy. So, checking the available ports brings unnecessary complexities.
This PR makes label `caddy.targetport` optional, and generates proxy directives without port, like:
```
proxy service_name
```
You can still override protocol with label `caddy.targetprotocol`, and can override port with label `caddy.targetport` and path with label `caddy.targetpath`. That generates directives like:
```
proxy protocol://service_name:port/path
```
Caddy will default protocol to http.
And then it will default port to protocol default port (http: 80, https: 443). …

Default proxy target port to caddy default behavior

---

plugin/generator.go
plugin/generator_test.go

This PR implements directives sorting useful when using Caddy [snippets](https://caddyserver.com/docs/caddyfile#snippets) and imports because the snippets must be defined before the directive which is importing it. This is especially useful when the snippets are coming from a different node that the directive. Luckily the snippets always start with `(` which puts them at the top of the sorted list.

Sort directives by their names

---

README.md
plugin/generator_test.go

Adding docs and tests, to ensure we never break that functionality.
@mcrosson

Document and add tests for generating empty labels with templates

---

README.md
main.go

Fixing issue https://github.com/lucaslorentz/caddy-docker-proxy/issues/85

Disable telemetry by default with options to enable it back

---

README.md
go.mod
main.go
plugin/loader.go
plugin/plugin.go
plugin/reloadcaddy_posix.go
plugin/reloadcaddy_windows.go

This pull request makes caddy-docker-proxy compatible with Caddy v1.0.1+ (see https://github.com/epicagency/caddy-expires/issues/6 for reference) by updating the import paths for Caddy and by bumping the version of the dnsproviders and caddy-cache plugins.

 Update the import paths for Caddy

---

Dockerfile-nanoserver-1809
build-images-windows.sh

Currently, you only have processes to build images for nanoserver 1803.  Unless the container host is setup to use hyperv isolation, these images will only work on a fairly narrow set of container hosts, as neither Server 2016 nor Server 2019 can run these images.  In my quick testing, using process isolation, Windows 10 1909 will run nanoserver 1809, 1903, and 1909, but not 1803.  Server 2016 will not run any of these, and Server 2019 will only run 1809.  Given that most server container hosts will either be running Server 2016 or Server 2019, adding nanoserver 1809 as an image would allow a significantly larger user base to make use of the images.
I am creating this as a draft release, because I am unsure what would need to be done to the azure pipelines file to allow the builds to …

Add 1809 docker images

---

plugin/caddyfile/fromlabels_test.go
plugin/caddyfile/processor_test.go
plugin/caddyfile/testdata/labels/follow_alphabetical_order.txt
plugin/caddyfile/testdata/labels/global_options.txt
plugin/caddyfile/testdata/labels/grouping.txt
plugin/caddyfile/testdata/labels/matchers_come_first.txt
plugin/caddyfile/testdata/labels/order_directives_with_prefix.txt
plugin/caddyfile/testdata/labels/separate_directives_with_suffix.txt
plugin/caddyfile/testdata/labels/snippets_come_first.txt
plugin/caddyfile/testdata/labels/template_error.txt
plugin/caddyfile/testdata/labels/templates_empty_values.txt
plugin/caddyfile/testdata/process/process.txt
plugin/generator/labels_test.go
plugin/generator/testdata/labels/all_special_labels.txt
plugin/generator/testdata/labels/doesnt_override_existing_proxy.txt
plugin/generator/testdata/labels/invalid_template.txt
plugin/generator/testdata/labels/minimum_special_labels.txt
plugin/generator/testdata/labels/multiple_addresses.txt
plugin/generator/testdata/labels/multiple_configs.txt
plugin/generator/testdata/labels/reverse_proxy_directives_are_moved_into_route.txt
plugin/generator/testdata/labels/with_groups.txt

As discussed previously, this refactors the tests that use labels or simple strings as inputs into files that contains the input/expected pairs.
I didn't bother touching the tests that have structs as input, I don't have a good way to clean those up while keeping the input/expected together.
This test strategy is something I set up for https://github.com/caddyserver/caddy, it's pretty much the same code for parsing the files. I also pulled the envfile parsing function that's in there as well, with a few modifications like trimming both sides and allowing whitespace around the `=`, because labels aren't as strict as env vars.

Refactor tests to use test files for input/expected pairs

---

plugin/caddyfile/caddyfile.go
plugin/caddyfile/fromlabels.go
plugin/caddyfile/fromlabels_test.go
plugin/caddyfile/marshal.go
plugin/caddyfile/marshal_test.go
plugin/caddyfile/merger.go
plugin/caddyfile/processor.go
plugin/caddyfile/processor_test.go
plugin/generator/containers.go
plugin/generator/generator.go
plugin/generator/labels.go
plugin/generator/labels_test.go
plugin/generator/services.go

Refactor to make Caddyfile representation more clear.
Align Caddyfile representation with official Caddy terminology.
This is only refactorings, no intended behavior changes.

Refactor Caddyfile representation

---

plugin/docker/utils.go
plugin/docker/utils_test.go

Hi @lucaslorentz. First of all, this looks like a great product! Unfortunately I haven't been able to use it out of the box as I failed at getting any reverse proxy setup to work. I tried to run the latest `standalone.yaml` example (both with versions `ci` and `3.2`) and encountered the following in the logs :
```
caddy-docker-demo_caddy.1.m2q5tf5tcbr5@my-laptop    | 2020/08/29 21:34:40 [INFO] Running caddy proxy server
caddy-docker-demo_caddy.1.m2q5tf5tcbr5@my-laptop    | {"level":"info","ts":1598736880.3025773,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}
caddy-docker-demo_caddy.1.m2q5tf5tcbr5@my-laptop    | {"level":"info","ts":1598736880.3028717,"msg":"autosaved …
```

Improved container id extraction from cgroups logic

---

plugin/caddyfile/caddyfile.go
plugin/caddyfile/marshal.go
plugin/caddyfile/testdata/labels/matchers_come_first.txt
plugin/caddyfile/testdata/labels/one_line_matchers_come_first.txt
tests/caddyfile+config/compose.yaml

If we declare something like:
```
whoami0:
image: jwilder/whoami
networks:
- caddy
deploy:
labels:
caddy: example.com
caddy.@matcher1.path: "*"
caddy.@matcher2.path: "/folder/*"
caddy.2_reverse_proxy: "@matcher1 {{upstreams 8000}}"
caddy.1_reverse_proxy: "@matcher2 {{upstreams 8000}}"
```
The marshaller will prioritize ordered directives over matchers. Generating:
```
example.com {
reverse_proxy @matcher2 10.0.3.8:8000
reverse_proxy @matcher1 10.0.3.6:8000
@matcher1 {
path *
}
@matcher2 {
path /folder/*
}
}
```
That behavior forces us to also define matchers order with #_ prefix.
This PR changes it to put matchers before other ordered directives. Generating this instead:
```
example.com {
@matcher1 {
path *
}
@matcher2 {
path /folder/*
}
reverse_proxy @matcher2 10.0.3.8:8000
reverse_proxy …
```

Ensure matchers are before ordered directives

---

README.md

I find the readme to be complex and it may be off-putting for other newcomers. The Examples/standalone.yaml seems to include swarm info (deploy / node etc) - perhaps I've misunderstood standalone - and so doesn't function in a simpler setup.
I've included the simplest docker-compose.yml files at top of Readme to show the easiest way to get this up and running and to encourage further reading. It's deliberately split out over 2 separate files to demonstrate that any new app created will automatically be picked up by Caddy (presumably through docker-gen?)

Basic example at top of Readme

---

plugin/cmd.go

I have a swarm deploy that uses [docker-socket-proxy](https://github.com/Tecnativa/docker-socket-proxy) for proxying all communication to the docker socket. Sometimes, when doing a full swarm re-deploy, my caddy containers would not apply the configuration specified in the docker labels, and would stay up with empty configurations, and the following error log:
```
{"level":"info","ts":1624826623.0097046,"logger":"docker-proxy","msg":"Running caddy proxy controller"}
{"level":"error","ts":1624826624.392478,"logger":"docker-proxy","msg":"Docker ping failed","error":"error during connect: Get \"http://docker_proxy:2375/_ping\": dial tcp: lookup docker_proxy on 127.0.0.11:53: no such host","errorVerbose":"Get \"http://docker_proxy:2375/_ping\": dial tcp: lookup docker_proxy on 127.0.0.11:53: …
```

Fix caddy hanging with empty config when unable to establish connection with docker during startup

---

plugin/generator/labels.go
plugin/generator/testdata/labels/h2c_reverse_proxy.txt

Currently the only protocols that are supported by this plugin are
`http` and `https` but Caddy itself does have support for `h2c` as well.

Added support for h2c protocol to upstreams

---

README.md
plugin/cmd.go
plugin/config/options.go
plugin/generator/generator.go
plugin/generator/generator_test.go
plugin/generator/services.go
plugin/loader.go

I tried to add an implementation for multiple docker sockets, related to the problem I opened on the topic.
I used your implementation and only changed the docker client to an array (and associated variables like jump events).
Could you please take a look at it, if it meets your principles?
Thanks

Multiple docker sockets support

---

plugin/generator/containers_test.go
plugin/generator/generator.go
plugin/generator/generator_test.go
plugin/generator/services_test.go

Hi there!
First, thanks a lot for this project, it is very useful!
When running `caddy-docker-proxy` without a Caddyfile or Swarm mode enabled, the log messages below are emitted every polling interval (default for 30s).
```
caddy_1  | {"level":"info","ts":1645116020.518531,"logger":"docker-proxy","msg":"Skipping swarm services because swarm is not available"}
caddy_1  | {"level":"info","ts":1645116050.5464995,"logger":"docker-proxy","msg":"Skipping default Caddyfile because no path is set"}
caddy_1  | {"level":"info","ts":1645116050.54652,"logger":"docker-proxy","msg":"Skipping swarm config caddyfiles because swarm is not available"}
caddy_1  | {"level":"info","ts":1645116050.5493286,"logger":"docker-proxy","msg":"Skipping swarm services because swarm is not available"}
caddy_1  | …
```

Change Caddyfile path not set and Swarm not available logs to Debug

---

README.md

Caddy 2.6.0 does not support single-hyphen long options https://github.com/caddyserver/caddy/pull/4565

Update Readme#Caddy CLI to use double-hyphen

---

README.md
loader.go

Unfortunately, doing so in Podman will sometimes lead to an EOF, causing the proxy to stop consuming events. This solves that issue with Podman compatibility.

Add ability to not send scopes as a filter with event listener

---

docker/utils.go
docker/utils_test.go

Use mountinfo, fallback to cgroups, fallback to hostname.
Fixes #207

Improve logic to find self container id

---

Dockerfile
Dockerfile-alpine

Current 3.15.4 image is flagged for CVE-2022-37434 per trivy scan

Update to use alpine 3.17 instead

---

README.md

Building with e.g. `github.com/lucaslorentz/caddy-docker-proxy/v2@2.7.0` does not work, the version pinning requires another `v` in front of the version number as in  `github.com/lucaslorentz/caddy-docker-proxy/v2@v2.7.0`

Fix pinned version module name example

---

README.md
generator/containers.go
generator/containers_test.go
generator/generator.go
generator/services.go
generator/services_test.go
tests/functions.sh
tests/ingress-networks/compose.yaml
tests/ingress-networks/run.sh
tests/standalone/compose.yaml
tests/standalone/run.sh

This PR adds support for overriding the ingress network for a container via a `caddy_ingress_network` label. Relates to #157
~Pushing this up for any early feedback - the code compiles, but I still need to test & add docs and tests are ready.~
Should be ready to go.

Per container ingress network override

---

cmd.go

Fixes https://github.com/lucaslorentz/caddy-docker-proxy/issues/556.
When we introduced "scan-stoped-containers" v2.8.7, it was intended to be false by default, but I accidentally enabled it by default.
Fixing this now. It is a breaking change for those who have been relying on it since 2.8.7, but a better behavior to have by default. More compatible with versions prior v2.8.7 as well.

Change scan-stopped-containers default value to false

---

module.go

Fixes #561.
```
...
docker_proxy v2.8.10
Non-standard modules: 1
...
```

Register docker_proxy caddy module

---

README.md
examples/distributed.yaml
examples/standalone.yaml
tests/caddyfile+config/compose.yaml
tests/containers/run.sh
tests/distributed/compose.yaml
tests/ingress-networks/compose.yaml
tests/process-caddyfile-off/compose_correct.yaml
tests/process-caddyfile-off/compose_wrong.yaml
tests/process-caddyfile-on/compose_wrong.yaml
tests/standalone/compose.yaml

containous/whoami is deprecated and there is no arm image available. traefik/whoami should be used.

Update the whoami source 

---

Dockerfile-alpine

Explicitly updated openssl as it had CVEs
#671

Updated alpine and openssl.

---

docker/client.go
docker/client_mock.go
generator/generator.go
generator/generator_test.go
generator/services_test.go
go.mod
go.sum

I try to build this with caddy-crowdsec-bouncer and #694 happened. I investigate the cause and found that this module has an outdated docker api version. Looking at #658 which is not solving the issue, I try to fix it and create this PR.
My custom caddy built successfully hence this PR.

update docker api and remove deprecated types

---

README.md

https://github.com/lucaslorentz/caddy-docker-proxy/issues/721

 For swarm services, labels should be inside deploy!

---

generator/generator.go

When `CADDY_DOCKER_LABEL_PREFIX` contains dots, parsing of blocks will break.
e.g. With `CADDY_DOCKER_LABEL_PREFIX=mydomain.gitlab.caddy`, cdp will yield error:
```
[ERROR]  Removing invalid block: Caddyfile:2: unrecognized global option: gitlab\n{\n\tgitlab {\n\t\tcaddy http://redis.gitlab.mydomain {\n\t\t\treverse_proxy 127.0.0.1:5540\n\t\t}\n\t}\n}\n\n
```
Then wrongly parsed block is:
```
{
gitlab {
caddy http://redis.gitlab.mydomain {
reverse_proxy 127.0.0.1:5540
}
}
}
```
It is because `gitlab.caddy` in `mydomain.gitlab.caddy` also gets parsed as path.
Using dots in prefix conforms to what docker has adopted in their labels, e.g.:
```
"com.docker.compose.project": "...",
"com.docker.compose.project.config_files": "...",
"com.docker.compose.project.working_dir": "...",
```
So using …

Fix broken block parsing when label prefix contains dots

---

README.md
examples/distributed.yaml
examples/standalone.yaml

Enable HTTP/3 by exposing port 443 for both TCP and UDP protocols to all Docker Compose examples.

Add UDP port mapping for HTTP/3 support

---

generator/generator.go
loader.go

I'm using https://git.sr.ht/~tomleb/docker-network-autoconnect to help manage networks between my applications (eg: bookstack, audiobookshelf, etc) and caddy. This means that the networks connected caddy are dynamically added/removed.
I found two problems with CDP, I fixed it with the commits here and that works for my use case.
1. CDP doesn't regenerates the Caddyfile when networks are connected/disconnected to caddy
2. The list of networks connected to caddy is computed once and reused.
This PR fixed both, by:
1. Reacting to docker network events. (This could be more specific eg: by filtering further the event to only caddy, but heh)
2. We're re-computing the list of networks every generation step
Not sure if this is needed or if this use case makes sense in general (probably though?), …

Update Caddyfile on network event
