- .travis.yml
- Dockerfile
- README.md
- build.sh
- glide.lock
Add Travis CI build.
Add build badge.
Add docker image publishing with versioning based on tags.
Update dependencies.
> Build improvements

- README.md
- glide.lock
- glide.yaml
- plugin/generator.go
- plugin/loader.go
@jakebailey Docker Api Version Negotiation works very well!
@jakebailey @ibnesayeed Can you please review?
> Update dependencies + Add Docker Api Version Negotiation

- plugin/generator.go
- plugin/generator_test.go
Fix https://github.com/lucaslorentz/caddy-docker-proxy/issues/33
> Fix unintended labels

- Dockerfile-alpine-arm32v6
- Dockerfile-arm32v6
- build.sh
- deploy-branch.sh
- deploy-tag.sh
Images for: https://github.com/lucaslorentz/caddy-docker-proxy/issues/39
@breadcat
> Add arm32v6 docker images

- README.md
- plugin/generator.go
- plugin/generator_test.go
Fixes https://github.com/lucaslorentz/caddy-docker-proxy/issues/44
> Add https backend support

- plugin/generator.go
- plugin/generator_test.go
This PR is trying to solve the issues #53.
> Adding support for configurable label prefix

- README.md
Fixes https://github.com/lucaslorentz/caddy-docker-proxy/issues/52
@cblomart
> Document proxying services vs containers

- README.md
- plugin/generator.go
- plugin/generator_test.go
- plugin/loader.go
Adding flag for the label prefix and documenting flags as discussed in PR #54.
> Adding doc for flags, flag for label prefix and env var for proxy flag

- .gitignore
- README.md
- examples/Caddyfile
- examples/container-proxy.yaml
- examples/service-proxy.yaml
- plugin/dockerclient.go
- plugin/generator.go
- plugin/generator_test.go
- plugin/loader.go
Fixes: https://github.com/lucaslorentz/caddy-docker-proxy/issues/23
It is available for test on docker image: lucaslorentz/caddy-docker-proxy:test
> Add config content to caddyfile

- plugin/generator.go
- plugin/generator_test.go
This PR fixes issues 2 and 3 reported on:
https://github.com/lucaslorentz/caddy-docker-proxy/issues/68
And second issue reported on:
https://github.com/lucaslorentz/caddy-docker-proxy/issues/67
Proxy directives still are generated whenever a `caddy.address` label is defined. This is an impact of making `caddy.targetport` optional. Any ideas on how to make port optional without causing this issue?
@jtyr @mrdrup
> Fix regressions with multiple addresses being merged

- plugin/loader.go
Because:
* Docker realtime events are working well to trigger caddy updates.
* Caddyfile generation is bigger now that we check containers, services and configs.
This PR:
* increases the default polling interval from 10s to 30s to save some resources.
* adds CLI flag and environment variable to set polling interval
The polling is a fallback in case an update was not triggered from a docker event.
@jtyr @mrdrup What do you think?
> Increase polling interval

- glide.lock
- main.go
- plugin/dockerutils.go
- plugin/generator.go
- plugin/generator_test.go
- plugin/loader.go
- plugin/reloadcaddy_posix.go
- plugin/reloadcaddy_windows.go
Update dependencies.
Add support for GetContainerId when running inside windows container.
Add experimental Caddy reload for windows.
Add lsiteners to container die event.
> Add windows containers support and reload

- README.md
- plugin/generator.go
Add cli command and env variable to use a default CaddyFile
Fix #78
> Add caddyfile path for default config

- plugin/generator.go
In my previous pull request there is a mistake that I fix in this one
> Fix typo in generator

- azure-pipelines.yml
> The go installation path changed on Azure devops

- Dockerfile
- Dockerfile-alpine
- Dockerfile-alpine-arm32v6
- Dockerfile-arm32v6
- go.mod
Update since caddy 1.0.2 contains security fixes.
Am I doing this right?
> Update to caddy 1.0.3 and alpine 3.10

- README.md
- plugin/caddyfileprocessor.go
- plugin/caddyfileprocessor_test.go
- plugin/generator.go
- plugin/generator_test.go
- plugin/loader.go
Fix #120
Working on validating each service independently.
I still need to run some tests, but it seems quite feasible.
@Maxiride
> Validate each service independently

- README.md
- plugin/generator.go
- plugin/generator_test.go
- plugin/go.mod
- plugin/go.sum
> Allow skip network validation

- README.md
- azure-pipelines.yml
- examples/example.yaml
- plugin/caddyfile/caddyfile.go
- plugin/caddyfile/fromlabels.go
- plugin/caddyfile/fromlabels_test.go
- plugin/generator/containers.go
- plugin/generator/containers_test.go
- plugin/generator/generator.go
- plugin/generator/labels.go
- plugin/generator/labels_test.go
- plugin/generator/services.go
- plugin/generator/services_test.go
- plugin/loader.go
Redesign to use more templates and remove custom labels
> Continue V2 improvements

- .editorconfig
- README.md
- examples/example.yaml
- plugin/caddyfile/caddyfile.go
- plugin/caddyfile/processor.go
- plugin/caddyfile/processor_test.go
- plugin/caddyfile/testdata/labels/global_options.txt
- plugin/caddyfile/testdata/labels/global_options_comes_first.txt
- plugin/caddyfile/testdata/process/process.txt
- plugin/generator/generator.go
- test-in-docker.sh
> Fix global options

- README.md
- plugin/caddyfile/marshal.go
- plugin/cmd.go
- plugin/generator/generator.go
- plugin/loader.go
- tests/caddyfile+config/compose.yaml
- tests/distributed/compose.yaml
- tests/empty/compose.yaml
- tests/process-caddyfile-off/compose_correct.yaml
- tests/process-caddyfile-off/compose_wrong.yaml
- tests/process-caddyfile-off/run.sh
- tests/process-caddyfile-on/compose_wrong.yaml
- tests/process-caddyfile-on/run.sh
- tests/run.sh
- tests/standalone/compose.yaml
Fixes https://github.com/lucaslorentz/caddy-docker-proxy/issues/153
> Ignore invalid caddyfile + change process-caddyfile default

- README.md
- plugin/cmd.go
- plugin/config/options.go
- plugin/docker/client.go
- plugin/docker/client_mock.go
- plugin/generator/containers.go
- plugin/generator/containers_test.go
- plugin/generator/generator.go
- plugin/generator/generator_test.go
- plugin/generator/services.go
- plugin/generator/services_test.go
- plugin/loader.go
- tests/ingress-networks/compose.yaml
- tests/ingress-networks/run.sh
> Replace validate networks option by manual definition of ingress networks

- examples/efs-volume.yaml
- examples/standalone.yaml
I have noticed, my automated yaml formatted made some changes.
I can revert those if not needed.
I have also grouped two changes into one commit.
- There seems to be a typo in the distributed example file
- I added some comments mostly to the standalone example file.
> clarifications to example yaml files

- azure-pipelines.yml
> Update to go 1.14.7

- README.md
- examples/standalone.yaml
Signed-off-by: Sven Dowideit <SvenDowideit@home.org.au>
> Note that configs: section is Docker Swarm only

- plugin/caddyfile/merge.go
- plugin/caddyfile/merge_test.go
- plugin/caddyfile/testdata/merge/php_fastcgi_different_matcher.txt
- plugin/caddyfile/testdata/merge/php_fastcgi_no_matcher.txt
- plugin/caddyfile/testdata/merge/php_fastcgi_same_matcher.txt
- plugin/caddyfile/testdata/merge/reverse_proxy_different_matcher.txt
- plugin/caddyfile/testdata/merge/reverse_proxy_no_matcher.txt
- plugin/caddyfile/testdata/merge/reverse_proxy_same_matcher.txt
Fixes https://github.com/lucaslorentz/caddy-docker-proxy/issues/191
> Merge php_fastcgi

- plugin/loader.go
- plugin/stringBoolCMap.go
- plugin/stringInt64CMap.go
- tests/functions.sh
Fix:
https://github.com/lucaslorentz/caddy-docker-proxy/issues/198
> Improve config updates towards servers

- plugin/docker/utils.go
- plugin/docker/utils_test.go
> Improve ID extraction to work on rootless docker

- plugin/cmd.go
- plugin/generator/containers.go
- plugin/generator/containers_test.go
- plugin/generator/generator.go
- plugin/generator/generator_test.go
- plugin/generator/services.go
- plugin/generator/services_test.go
- plugin/go.mod
- plugin/go.sum
- plugin/loader.go
> use zap logger

- README.md
Not a super friendly description. I'm not inspired 😄
> Fixes #235

- README.md
These fixes should help with overall readability of the document.
> Grammatical Fixes to README.md

- README.md
- plugin/cmd.go
- plugin/loader.go
> Fix DOCKER_HOST support

- Dockerfile-alpine
Fix https://github.com/lucaslorentz/caddy-docker-proxy/issues/372
> Add back curl to alpine image

- dependabot.yml
Adding dependabot to test it, maybe it will make it even simpler to keep caddy up to date
> Add dependabot

- README.md
Change the plugin name and sync content from Dockerfile-alpine
> Update README about build image

- generator/generator.go
- generator/generator_test.go
> Compare network name as well to support podman

- README.md
- cmd.go
- config/options.go
- loader.go
> Allow customizing the throttle interval for events

- Dockerfile
- Dockerfile-alpine
> Update alpine base image and revert openssl install

- .github/workflows/ci-pipeline.yaml
- cmd.go
> Fix mode cli arg
